### ISSUE TITLE
Failure to install due to incorrect naming scheme

### ISSUE THREAD

**Issue by heydonovan** [draios/terraform-provider-sysdig#18]
The URL I'm using to download the plugin: https://github.com/draios/terraform-provider-sysdig/releases/download/v0.2.0/terraform-provider-sysdig-darwin-amd64

The filename should be `terraform-provider-sysdig_v0.2.0` instead of `terraform-provider-sysdig-darwin-amd64`.

**Comment by tembleking** [comment]
Hi @heydonovan, thanks for your feedback.

The naming in the releases is just an indicator of the Operating system and the Architecture of the precompiled binary.
We can find a better approach to this, maybe packaging the binary with this name you suggest in a .tar.gz file with the operating system and the architecture.
