### ISSUE TITLE
Add capture on/off and nothing (notify only) option

### ISSUE THREAD

**Issue by heydonovan** [draios/terraform-provider-sysdig#20]
This is for the `sysdig_secure_policy` resource. :v:

**Comment by tembleking** [comment]
Hi @heydonovan, thanks for your feedback.

You can enable the notification defining [Notification Channels](https://github.com/draios/terraform-provider-sysdig/blob/1071a0cfabf5541931cd4ef5182f903f8ea3dce4/website/docs/r/sysdig_secure_policy.html.markdown#notification) for this Policy.

If you need to enable captures, define the [`actions` block](https://github.com/draios/terraform-provider-sysdig/blob/1071a0cfabf5541931cd4ef5182f903f8ea3dce4/website/docs/r/sysdig_secure_policy.html.markdown#actions-block) and define a `capture` with the required `seconds_before_event` and `seconds_after_event`.

I'll close this issue but feel free to reopen it and we can discuss about it.
