### ISSUE TITLE
API Tokens should only be required for the service being used

### ISSUE THREAD

**Issue by steven-terrana** [draios/terraform-provider-sysdig#23]
Hello!

Great job on this provider, thank you! 

If feasible, it would be awesome if API Tokens for only the Sysdig services being consumed were required. 

For example, in my use case, I am only configuring Sysdig Secure rules and policies but I am still required to provide a value for `sysdig_monitor_api_token`. 

This is not a blocker, as i can set that value to an arbitrary value since it will not be utilized. 

Ideally, `sysdig_secure_api_token` would only be required if actually needed based upon the resources to be created and same for `sysdig_monitor_api_token`.

**Comment by steven-terrana** [comment]
Hoping this is a small lift - i'm new to terraform and go but i'll take a look into provider configuration options when i get a chance to see if i can resolve this. 

PRs >> issues :).

**Comment by danpopSD** [comment]
@nestorsalceda ^^

**Comment by tembleking** [comment]
Thanks for your comment @steven-terrana, we will think about the approach and create a PR asap to fix this

**Comment by tembleking** [comment]
Fixed in https://github.com/draios/terraform-provider-sysdig/commit/9629889708bf2a10fde02fae5fb411c4b1768b19.
