### ISSUE TITLE
Fix `rpc error: code = Unavailable desc`

### ISSUE THREAD

**Issue by ukitazume** [draios/terraform-provider-sysdig#30]
it was mentioned at #29. 
When I run `terraform apply`, frequently, I see the error `Error: rpc error: code = Unavailable desc = transport is closing` .

I've attached the `TF_LOG=debug terraform apply >> neterror.log 2>&1` output.

[neterror.log](https://github.com/draios/terraform-provider-sysdig/files/4676162/neterror.log)

**Comment by tembleking** [comment]
Hi @ukitazume, thanks for the feedback.

I ran the tests with the race condition checker enabled and I think I found the root problem.
The Terraform Plugin SDK has a race condition while writing and reading from the map of properties defined from the user.

I believe that this commit fixes it: https://github.com/draios/terraform-provider-sysdig/commit/290e398440f442388bca19e8243618f689ef9e26 Can you give it a try?

**Comment by ukitazume** [comment]
Hi, @tembleking thank you for the quick fix. I will try it and let you know the result.

**Comment by ukitazume** [comment]
It works. it success 10 times with the below command. 
` for i in {1..10}; do; terraform apply -auto-approve; done`

**Comment by tembleking** [comment]
Thanks for trying it @ukitazume, I will close this issue then :slightly_smiling_face:
